####2. Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
####1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
####By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

last = 1
current = 2

results = [2]
while current < 4000000
  x = current + last
  if x % 2 == 0
  	results.push(x)
  end
  last = current
  current = x
end

total = results.inject(:+)
puts total
